import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const onAirVar = localFont({
  src: [
    {
      path: "../../public/OnAirVar.woff",
    },
    {
      path: "../../public/OnAirVar.woff2",
    },
  ],
  variable: "--font-on-air-var",
  fallback: ["sans-serif"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onAirVar.variable} antialiased font-[family-name:var(--font-on-air-var)]`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
